from datetime import datetime


def render_review_md(run_id: str, stage_name: str, label: str,
                     artifact_summary: str = "") -> str:
    """Render a GATE_REVIEW.md template for human approval."""
    now = datetime.now().isoformat()

    lines = [
        f"# {label}",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Run ID** | `{run_id}` |",
        f"| **Stage** | `{stage_name}` |",
        f"| **Created** | {now} |",
        f"| **Status** | Pending Review |",
        "",
        "## Artifact Preview",
        "",
    ]

    if artifact_summary:
        lines.append("```json")
        # Truncate very large artifacts for readability
        if len(artifact_summary) > 5000:
            lines.append(artifact_summary[:5000])
            lines.append("... (truncated, see full artifact in workspace)")
        else:
            lines.append(artifact_summary)
        lines.append("```")
    else:
        lines.append("_(No artifact available yet)_")

    lines.extend([
        "",
        "## Decision",
        "",
        "To approve or reject this stage, use the CLI:",
        "",
        "```bash",
        f"# Approve",
        f"factory approve {run_id} {stage_name}",
        "",
        f"# Reject with reason",
        f"factory reject {run_id} {stage_name} --reason \"Not what I expected\"",
        "",
        f"# Request changes",
        f"factory changes {run_id} {stage_name} --feedback \"Please add error handling\"",
        "```",
        "",
        "Or edit the DECISION file directly:",
        "",
        "```bash",
        f"echo 'approved' > workspace/gates/{run_id}/{stage_name}/DECISION",
        f"echo 'rejected' > workspace/gates/{run_id}/{stage_name}/DECISION",
        f"echo 'changes_requested' > workspace/gates/{run_id}/{stage_name}/DECISION",
        "```",
        "",
        "---",
        f"_Generated by AI Factory at {now}_",
    ])

    return "\n".join(lines)
